# Generated by Django 6.1 on 2026-09-04 03:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='capa',
        ),
        migrations.AddField(
            model_name='produto',
            name='alt_text_capa',
            field=models.CharField(default='imagem', max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
