# Generated by Django 6.1 on 2026-09-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_imagem_capa_produto_alt_text_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='alt_text_capa',
            field=models.CharField(default='imagem do produto', max_length=255),
        ),
    ]
