# Generated by Django 6.1 on 2026-09-10 23:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produto_destaque_alter_produto_alt_text_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
