# Generated by Django 6.1 on 2026-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categoria_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produto_tipo',
            field=models.CharField(choices=[('canecas', 'Canecas'), ('brincos', 'Brincos'), ('bottoms', 'Bottoms'), ('chaveiros', 'Chaveiros')], default='copos', max_length=200),
        ),
    ]
