# Generated by Django 6.1 on 2026-10-06 02:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_produto_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=cloudinary.models.CloudinaryField(default='default08', max_length=255),
        ),
    ]
