# Generated by Django 6.1 on 2026-10-06 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_imagem_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('convertido', 'Convertido em Pedido'), ('abandonado', 'Abandonado')], default='ativo', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.carrinho')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_carrinho', to='app.produto')),
            ],
            options={
                'ordering': ['adicionado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='carrinho',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativo'), ('usuario__isnull', False)), fields=('usuario',), name='unique_carrinho_ativo_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='carrinho',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativo'), ('session_key__isnull', False)), fields=('session_key',), name='unique_carrinho_ativo_por_session'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrinho',
            constraint=models.UniqueConstraint(condition=models.Q(('produto__isnull', False)), fields=('carrinho', 'produto'), name='unique_produto_por_carrinho'),
        ),
    ]
