# Generated by Django 6.1 on 2026-10-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_carrinho_itemcarrinho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='apelido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
