# Generated by Django 6.1 on 2026-10-07 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_endereco_apelido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('em_preparacao', 'Aguardando Envio'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('falha_pagamento', 'Falha no Pagamento')], default='pendente_pagamento', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], max_length=20, null=True)),
                ('id_transacao_gateway', models.CharField(blank=True, max_length=120, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_produtos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frete_transportadora', models.CharField(blank=True, max_length=80, null=True)),
                ('frete_prazo_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entrega_apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('entrega_cep', models.CharField(max_length=9)),
                ('entrega_endereco', models.CharField(max_length=255)),
                ('entrega_numero', models.CharField(max_length=20)),
                ('entrega_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('entrega_bairro', models.CharField(max_length=100)),
                ('entrega_cidade', models.CharField(max_length=100)),
                ('entrega_estado', models.CharField(max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('carrinho_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='app.carrinho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='app.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.pedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-criado_em'], name='app_pedido_usuario_520e75_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'expira_em'], name='app_pedido_status_7ecf23_idx'),
        ),
    ]
