# Generated by Django 6.1 on 2026-10-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='limite_alteracao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_foto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
